services:
  postgres:
    image: 'postgres:17.2'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '9931:5432'
